baseURL = "http://example.org/"
languageCode = "en-us"
title = "Project Geode"
theme = "hugo-theme-docdock"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
themeStyle = "flex"
themeVariant = "gray"